// config/therapists.js
// Clinician profiles. Shared by the home page preview, /therapists,
// and each /therapists/[slug] profile page.
// Placeholder content — replace with real clinicians per project.
//
// photo: { src, alt, width, height } or null (null shows an initials avatar)
// acceptingClients: true shows "Accepting new clients", false shows "Waitlist"

const therapists = [
	{
		slug: "omar-haddad",
		name: "Omar Haddad",
		firstName: "Omar",
		credentials: "PsyD",
		pronouns: "he/him",
		title: "Licensed Clinical Psychologist",
		photo: {
			src: "/home/profile-hero.jpg",
			alt: "Omar Haddad, smiling, wearing glasses and a dark blazer",
			width: 2853,
			height: 2853,
		},
		acceptingClients: true,
		bio: [
			"Omar works with adults who feel stuck — whether that looks like persistent worry, a low mood that won't lift, or a major life change that has shaken their sense of direction. He believes therapy works best when it is collaborative, practical, and grounded in the realities of a client's life and culture.",
			"His approach blends cognitive behavioral therapy with acceptance-based tools, helping clients understand their patterns and build skills they can use between sessions. Omar has a particular interest in men's mental health and in supporting clients navigating bicultural identity.",
		],
		specialties: [
			"Anxiety",
			"Depression",
			"Life transitions",
			"Men's mental health",
			"Cultural identity",
		],
		approaches: [
			"Cognitive Behavioral Therapy (CBT)",
			"Acceptance and Commitment Therapy (ACT)",
			"Psychodynamic therapy",
		],
		populations: ["Adults", "Young adults (18–25)"],
		languages: ["English", "Arabic"],
		sessionFormats: ["In person", "Virtual"],
		location: "Main office",
		insurance: ["Aetna", "Blue Cross Blue Shield", "Out-of-network"],
	},
	{
		slug: "amira-hassan",
		name: "Amira Hassan",
		firstName: "Amira",
		credentials: "LCSW",
		pronouns: "she/her",
		title: "Licensed Clinical Social Worker",
		photo: {
			src: "/hero/variant-c1.jpg",
			alt: "Amira Hassan, smiling, wearing a patterned headscarf",
			width: 4480,
			height: 6720,
		},
		acceptingClients: true,
		bio: [
			"Amira specializes in helping people heal from trauma and loss. She creates a steady, unhurried space where clients can move at their own pace, and she pays close attention to how faith, family, and community shape each person's story.",
			"Amira is trained in EMDR and trauma-focused CBT, and she integrates mindfulness practices to help clients feel more at home in their bodies. She works with adults and teens ages 13 and up.",
		],
		specialties: [
			"Trauma and PTSD",
			"Grief and loss",
			"Anxiety",
			"Women's issues",
			"Faith and spirituality",
		],
		approaches: [
			"EMDR",
			"Trauma-focused CBT",
			"Mindfulness-based therapy",
		],
		populations: ["Adolescents (13+)", "Adults"],
		languages: ["English", "Arabic"],
		sessionFormats: ["In person", "Virtual"],
		location: "Main office",
		insurance: ["Cigna", "UnitedHealthcare", "Out-of-network"],
	},
	{
		slug: "daniel-chen",
		name: "Daniel Chen",
		firstName: "Daniel",
		credentials: "LMFT",
		pronouns: "he/him",
		title: "Licensed Marriage and Family Therapist",
		photo: {
			src: "/hero/variant-abd.jpg",
			alt: "Daniel Chen, smiling, seated in a dark blazer",
			width: 3456,
			height: 5184,
		},
		acceptingClients: false,
		bio: [
			"Daniel helps couples and families break out of painful cycles and reconnect. Whether partners are facing constant conflict, a breach of trust, or simply feel like roommates, he helps each person feel heard while working toward change together.",
			"He draws on Emotionally Focused Therapy and the Gottman Method, and he brings a family systems lens to work with parents and adult children. Daniel also supports Asian American clients navigating family expectations and identity.",
		],
		specialties: [
			"Couples therapy",
			"Family conflict",
			"Communication",
			"Life transitions",
			"Asian American identity",
		],
		approaches: [
			"Emotionally Focused Therapy (EFT)",
			"Gottman Method",
			"Family systems therapy",
		],
		populations: ["Couples", "Families", "Adults"],
		languages: ["English", "Mandarin"],
		sessionFormats: ["In person", "Virtual"],
		location: "Main office",
		insurance: ["Out-of-network"],
	},
	{
		slug: "maria-rodriguez",
		name: "María Rodríguez",
		firstName: "María",
		credentials: "LPC",
		pronouns: "she/her",
		title: "Licensed Professional Counselor",
		photo: null,
		acceptingClients: true,
		bio: [
			"María supports adults through depression, anxiety, and the many adjustments of parenthood — from pregnancy and the postpartum period to raising teenagers. She is warm, direct, and focused on helping clients find small, sustainable steps forward.",
			"She offers therapy in English and Spanish and has a special interest in the stress that comes with immigration and living between cultures. María sees clients virtually across the state.",
		],
		specialties: [
			"Depression",
			"Perinatal and postpartum",
			"Anxiety",
			"Parenting",
			"Immigration stress",
		],
		approaches: [
			"Cognitive Behavioral Therapy (CBT)",
			"Person-centered therapy",
			"Solution-focused therapy",
		],
		populations: ["Adults", "Parents"],
		languages: ["English", "Spanish"],
		sessionFormats: ["Virtual"],
		location: "Virtual only",
		insurance: ["Aetna", "Medicaid", "Out-of-network"],
	},
	{
		slug: "jordan-ellis",
		name: "Jordan Ellis",
		firstName: "Jordan",
		credentials: "LCSW",
		pronouns: "they/them",
		title: "Licensed Clinical Social Worker",
		photo: null,
		acceptingClients: true,
		bio: [
			"Jordan provides affirming care for LGBTQ+ teens and adults, with a focus on gender identity, anxiety, and recovering from difficult experiences. They believe every client is the expert on their own life and work to make therapy a place where people can show up fully.",
			"Jordan is trained in Dialectical Behavior Therapy and Internal Family Systems, and they often help clients build skills for managing intense emotions while exploring the deeper roots of their pain.",
		],
		specialties: [
			"LGBTQ+ affirming care",
			"Gender identity",
			"Anxiety",
			"Depression",
			"Trauma and PTSD",
		],
		approaches: [
			"Dialectical Behavior Therapy (DBT)",
			"Internal Family Systems (IFS)",
			"Acceptance and Commitment Therapy (ACT)",
		],
		populations: ["Adolescents (13+)", "Young adults (18–25)", "Adults"],
		languages: ["English"],
		sessionFormats: ["In person", "Virtual"],
		location: "Main office",
		insurance: ["Blue Cross Blue Shield", "Cigna", "Out-of-network"],
	},
	{
		slug: "rachel-goldberg",
		name: "Rachel Goldberg",
		firstName: "Rachel",
		credentials: "PhD",
		pronouns: "she/her",
		title: "Licensed Psychologist",
		photo: null,
		acceptingClients: false,
		bio: [
			"Rachel specializes in OCD, anxiety disorders, and perfectionism. She helps clients understand how avoidance keeps anxiety going and guides them, step by step, toward the things that matter to them.",
			"Her work is grounded in Exposure and Response Prevention and CBT, with DBT skills woven in for clients who struggle with intense emotions. Rachel also works with teens and adults with ADHD and disordered eating.",
		],
		specialties: [
			"OCD",
			"Anxiety",
			"Perfectionism",
			"ADHD",
			"Eating disorders",
		],
		approaches: [
			"Exposure and Response Prevention (ERP)",
			"Cognitive Behavioral Therapy (CBT)",
			"DBT skills",
		],
		populations: ["Adolescents (13+)", "Adults"],
		languages: ["English", "Hebrew"],
		sessionFormats: ["In person", "Virtual"],
		location: "Main office",
		insurance: ["Out-of-network"],
	},
];

export default therapists;
